config/routes.rb
Blog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  resources :tags do
    get 'tag_posts', :on => :member
  end

  resources :posts do
    resources :comments
  end

  namespace :admin do
    root :to => 'posts#index'
    resources :users
    resources :posts
    resources :tags
    get '/:slug' => 'posts#show', :as => :slug
    post '/upload' => 'posts#upload'
  end

  get '/:slug' => 'posts#show', :as => :slug

  get 'posts/feed' => 'posts#feed'

  get 'home/index' => 'home#index'

  root :to => 'posts#index', :as => 'root'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order("created_at desc").page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, wrapper: :bootstrap, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= f.button :cancel, to: users_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% @title = "Editing user" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% @title = "Listing users" %>

<% content_for :actions do %>
  <%= link_to new_user_registration_path, class: 'btn btn-primary btn-large pull-right' do %>
    <%= icon_tag "plus" %> Add User
  <% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td class="actions">
            <%= link_to icon_tag("trash"), user, rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->
<%= paginate @users %>

app/views/users/new.html.erb
<% @title = "New user" %>

<%= render 'form' %>

app/views/users/show.html.erb
<% @title = "Showing user" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Email</label>
    <div class="controls">
      <span class="span6"><%= @user.email %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_user_path(@user), class: 'btn btn-primary' %>
    <%= link_to 'Back', users_path, class: 'btn' %>
  </div>
</div>