config/routes.rb
Blog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  resources :tags do
    get 'tag_posts', :on => :member
  end

  resources :posts do
    resources :comments
  end

  namespace :admin do
    root :to => 'posts#index'
    resources :users
    resources :posts
    resources :tags
    get '/:slug' => 'posts#show', :as => :slug
    post '/upload' => 'posts#upload'
  end

  get '/:slug' => 'posts#show', :as => :slug

  get 'posts/feed' => 'posts#feed'

  get 'home/index' => 'home#index'

  root :to => 'posts#index', :as => 'root'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :post_tag_mappings
  has_many :posts, :through => :post_tag_mappings
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order("created_at desc").page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tags_path, notice: 'Tag was successfully created.' }
        format.json { render json: admin_tags_path, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to admin_tags_path, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to admin_tags_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "colorless"
  
  def tag_posts
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.order("created_at desc").page(params[:page]).per(10)
    @tags = Tag.all
  end
  
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= simple_form_for([:admin, @tag], wrapper: :bootstrap, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= f.button :cancel, to: admin_tags_path %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<% @title = "Editing tag" %>

<%= render 'form' %>

app/views/admin/tags/index.html.erb
<% @title = "标签列表" %>

<% content_for :actions do %>
<%= link_to new_admin_tag_path, class: 'btn btn-primary btn-large pull-right' do %>
    <%= icon_tag "plus" %> Add Tag
  <% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td class="actions">
            <%= link_to icon_tag("eye-open"), [:admin, tag], rel: 'tooltip', title: 'Show' %>
            <%= link_to icon_tag("pencil"), edit_admin_tag_path(tag), rel: 'tooltip', title: 'Edit' %>
            <%= link_to icon_tag("trash"), [:admin, tag], rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->
<%= paginate @tags %>

app/views/admin/tags/new.html.erb
<% @title = "New tag" %>

<%= render 'form' %>

app/views/admin/tags/show.html.erb
<% @title = "Showing tag" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls">
      <span class="span6"><%= @tag.name %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_admin_tag_path(@tag), class: 'btn btn-primary' %>
    <%= link_to 'Back', admin_tags_path, class: 'btn' %>
  </div>
</div>