config/routes.rb
Blog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  resources :tags do
    get 'tag_posts', :on => :member
  end

  resources :posts do
    resources :comments
  end

  namespace :admin do
    root :to => 'posts#index'
    resources :users
    resources :posts
    resources :tags
    get '/:slug' => 'posts#show', :as => :slug
    post '/upload' => 'posts#upload'
  end

  get '/:slug' => 'posts#show', :as => :slug

  get 'posts/feed' => 'posts#feed'

  get 'home/index' => 'home#index'

  root :to => 'posts#index', :as => 'root'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :slug, :title
  #mount_uploader :file, ImageUploader

  has_many :post_tag_mappings
  has_many :tags, :through => :post_tag_mappings
  has_many :comments

  #validates :slug, :presence => true
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at desc").page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }

    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_slug(params[:slug])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
    @tags = Tag.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tags = Tag.all
  end

  def create
    @post = Post.new(params[:post])
    tags = params[:tags]

    respond_to do |format|
      if @post.save
        @post.tag_ids = tags
        format.html { redirect_to admin_slug_path(@post.slug), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    tags = params[:tags]

    respond_to do |format|
      if @post.update_attributes(params[:post])
         @post.tag_ids = tags
        format.html { redirect_to admin_slug_path(@post.slug), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_path }
      format.json { head :no_content }
    end
  end

  def upload
    #debugger
    uploader = ImageUploader.new

    if uploader.store!(params[:file])
      render :json => {:filelink => "/uploads/blog/pictures/#{params[:file].original_filename}"}
    else
      render json: 'upload error', status: :unprocessable_entity
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "colorless"
  before_filter :find_tags

  def index
    @posts = Post.order("created_at desc").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.rss { render :layout => false }
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find_by_slug(params[:slug])
    @comments = @post.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  def feed
    @posts = Post.order("created_at desc")
    
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_articles.html.erb
<% @posts.each do |post| %>
   <article class="notebook audio">
       <h2><%= link_to post.title, slug_path(post.slug) %></h2><div class="triangle"></div>
         <div class="row-fluid">
           <div>
              <div class="jqDnR" id="idTextPanel">
                <%= post.content.html_safe %>
              </div>
           </div>
         </div>
         <footer>
           <div class="row-fluid">
              <span class="posted-on span4"><i class="social-calendar"></i><%= post.created_at.strftime("%Y-%m-%d") %></span>
              <div class="social span8 pull-right">
                <div class="comment-count span4 pull-right"><i class="social-comments"></i>
                  <%= link_to slug_path(post.slug, :anchor => "comment") do %>
                    <%= post.comments.count %> Comments
                  <% end %>
                </div>
              </div>
            </div>
          </footer>

  </article>
<% end %>

app/views/posts/_comment.html.erb
<section class="comments notebook" id="comment">
  <div class='layout'>
    <nav id="global-nav">
      <ul class="publisher-anchor-hover">
        <li class="active" data-role="global-nav">
          <a id="post-count" data-nav="conversation" href="#">
            <h4><%= @comments.count %> <%= @comments.count >1 ? 'comments' : 'comment' %></h4>
          </a>
        </li>
      </ul>
    </nav>
    <div id="form">
      <div class="reply expanded">
        <div class='postbox'>
          <div class='avatar'>
            <span class='user'>
              <img src="/assets/colorless/avatar-comment.png" data-role="user-avatar">
            </span>
          </div>
          <%= render "posts/comment_form" %>
        </div>
        
      </div>
    </div>
    <div id='main-nav' class='nav'>
      <ul>
        <li class="dropdown active" data-dropdown="enabled">
          <a class="dropdown-toggle publisher-nav-color" data-toggle="dropdown" data-nav="conversation" href="#">
            Discussion
            <span class="caret"></span>
            <span class="divider"></span>
          </a>
        </li>
      </ul>
    </div>
    <%= render "posts/comment_list" %>
  </div>
</section>


<% content_for :styles do %>
  <%= stylesheet_link_tag "colorless/comment" %>
<% end %>

app/views/posts/_comment_form.html.erb
<%= form_for([@post, @comment],:remote =>true) do |f| %>
  <%= f.error_notification %>
  <div class="textarea-wrapper" data-role="textarea">
    <%= f.text_area :context, :required =>true, :class => 'textarea-input', :placeholder => 'Leave a message...' %>
    <div class="post-actions">
      <%= f.text_field :name, :required =>true, :placeholder => 'Name' %>
      <%= f.button "Post", :class => 'btn submit' %>
    </div>
  </div>
<% end %>

app/views/posts/_comment_list.html.erb
<section id='conversation' data-role='main'>
  <div id="posts">
    <ul id="post-list" class="post-list">
      <% @comments.each do |comment| %>
      <% if comment.reply_user.nil?  %>
      <li class='post'>
        <div class="post-content " data-role="post-content">
          <div class="indicator"></div>
          <div class="avatar">
            <div class="user">
              <img class="user" alt="Avatar" src="/assets/colorless/avatar-comment.png" />
            </div>
          </div>
          <div class='post-body'>
            <header>
              <span class="name"><%= comment.name %></span>
              <span class="bullet" aria-hidden="true">•</span>
              <a class="time-ago" title="Monday, January 28 2013 5:38 PM" data-role="relative-time" href="#comment-780446315"> <%= comment.created_at.strftime("%Y-%m-%d") %> </a>
              <a class="pull-right" href="#myModal<%= comment.id %>" data-backdrop="static" data-toggle="modal">reply</a>
              <div id="myModal<%= comment.id %>" class="modal hide" style="display: none;" aria-hidden="true">
                <div class="modal-header">
                  <button class="close" data-dismiss="modal">×</button>
                  <h3>回复 <%= comment.name %>:</h3>
                </div>
                 <%= simple_form_for([@post, @comment],:remote =>true) do |f| %>
                 <%= f.hidden_field :parent_id, value:comment.id %>
                 <%= f.hidden_field :reply_user, value:comment.name %>
                <div class="modal-body"> 
                  <%= f.input :name, :required =>true, :placeholder => 'Name' %>           
                  <%= f.input :context, :required =>true, :input_html => {:rows => 7, :class =>'textarea-input_ap'} %>           
                 </div>
                <div class="modal-footer">
                  <%= f.submit '提交', :class => 'btn btn-primary btn-info' %>
                </div>
                 <% end %>  
              </div>
            </header>
            <div class="post-message-container" data-role="message-container">
              <div class="post-message publisher-anchor-color " data-role="message">
                <p><%= comment.context %></p>
              </div>
            </div>
          </div>
        </div>
        <% comment.son_comments.each do |son_comment| %>
        <ul class="children" data-role="children">
          <li class='post'>
            <div class="post-content " data-role="post-content">
            <div class="indicator"></div>
            <div class="avatar">
              <div class="user">
                <img class="user" alt="Avatar" src="/assets/colorless/avatar-comment.png" />
              </div>
            </div>
            <div class='post-body' style="margin-left:30px;">
              <header>
                <span class="name"><%= son_comment.name %></span>
                <span>               
                <i class="icon-forward" title="in reply to" aria-hidden="true"></i>
                <%= son_comment.reply_user %>
                </span>
                <span class="bullet" aria-hidden="true">•</span>
                <a class="time-ago" title="Monday, January 28 2013 5:38 PM" data-role="relative-time" href="#comment-780446315"> <%= son_comment.created_at.strftime("%Y-%m-%d") %> </a>
                <a class="pull-right" href="#myModal<%= son_comment.id %>" data-backdrop="static" data-toggle="modal">reply</a>
                <div id="myModal<%= son_comment.id %>" class="modal hide" style="display: none;" aria-hidden="true">
                  <div class="modal-header">
                    <button class="close" data-dismiss="modal">×</button>
                    <h3>回复 <%= son_comment.name %>:</h3>
                  </div>
                   <%= simple_form_for([@post, @comment],:remote =>true) do |f| %>
                   <%= f.hidden_field :parent_id, value:comment.id %>
                   <%= f.hidden_field :reply_user, value:son_comment.name %>
                  <div class="modal-body"> 
                    <%= f.input :name, :required =>true, :placeholder => 'Name' %>           
                    <%= f.input :context, :required =>true, :input_html => {:rows => 7, :class =>'textarea-input_ap'} %>           
                   </div>
                  <div class="modal-footer">
                    <%= f.submit '提交', :class => 'btn btn-primary btn-info' %>
                  </div>
                   <% end %>  
                </div>
              </header>
              <div class="post-message-container" data-role="message-container">
                <div class="post-message publisher-anchor-color " data-role="message">
                  <p><%= son_comment.context %></p>
                </div>
              </div>
            </div>
          </div>
          </li>
        </ul>
        <% end %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/posts/_form.html.erb
<% content_for :javascript do %>  
  <%= javascript_include_tag "redactor.min" %>
  <%= javascript_include_tag "redactor_custom" %>
<% end %>
<% content_for :head do %>
  <%= stylesheet_link_tag "redactor" %>
<% end %>
<%= simple_form_for(@post, wrapper: :bootstrap, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, :required =>true, :input_html => {:class => 'span6'} %>
    <%= f.input :context, :required =>true, :input_html => {:row => 50}  %>
    <%= f.input :slug, :required =>true, :input_html => {:class => 'span6'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= f.button :cancel, to: posts_path %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="row-fluid">
  <div class="span8">
    <%= render "posts/articles" %>
    <div class="row-fluid">
      <%= paginate @posts %>
    </div>
  </div>
  <%= render "layouts/aside" %>
</div>

app/views/posts/show.html.erb
<div class="row-fluid">
  <div class="span8">
    <article class="notebook audio">
       <h2><%= link_to @post.title, slug_path(@post.slug) %></h2><div class="triangle"></div>
         <div class="row-fluid">
           <div>
              <div class="jqDnR" id="idTextPanel">
                <%= @post.content.html_safe %>
              </div>
           </div>
         </div>
         <footer>
           <div class="row-fluid">
              <span class="posted-on span4"><i class="social-calendar"></i><%= @post.created_at.strftime("%Y-%m-%d") %></span>
              <div class="social span8 pull-right">
                <div class="comment-count span4 pull-right"><i class="social-comments"></i>
                  <%= link_to slug_path(@post.slug, :anchor => "comment") do %>
                    <%= @post.comments.count %> Comments
                  <% end %>
                </div>

              </div>

            </div>
          </footer>
      </article>
      <%= render "posts/comment" %>
  </div>
  <%= render "layouts/aside" %>
</div>