config/routes.rb
Blog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  resources :tags do
    get 'tag_posts', :on => :member
  end

  resources :posts do
    resources :comments
  end

  namespace :admin do
    root :to => 'posts#index'
    resources :users
    resources :posts
    resources :tags
    get '/:slug' => 'posts#show', :as => :slug
    post '/upload' => 'posts#upload'
  end

  get '/:slug' => 'posts#show', :as => :slug

  get 'posts/feed' => 'posts#feed'

  get 'home/index' => 'home#index'

  root :to => 'posts#index', :as => 'root'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :context, :name, :parent_id, :reply_user
  has_many :son_comments, :class_name => 'Comment', :foreign_key => 'parent_id'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :slug, :title
  #mount_uploader :file, ImageUploader

  has_many :post_tag_mappings
  has_many :tags, :through => :post_tag_mappings
  has_many :comments

  #validates :slug, :presence => true
end

app/models/post_tag_mapping.rb
class PostTagMapping < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
  # attr_accessible :title, :body
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
  load!
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :post_tag_mappings
  has_many :posts, :through => :post_tag_mappings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def find_tags
    @tags = Tag.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    respond_to do |f|
      f.js{
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(params[:comment])
        
        unless @comment.save
          render :text => :error, :status => :unprocessable_entity
        end
      }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "colorless"
  before_filter :find_tags

  def index
    @posts = Post.order("created_at desc").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.rss { render :layout => false }
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find_by_slug(params[:slug])
    @comments = @post.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  def feed
    @posts = Post.order("created_at desc")
    
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "colorless"
  
  def tag_posts
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.order("created_at desc").page(params[:page]).per(10)
    @tags = Tag.all
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order("created_at desc").page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    "My App"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_aside.html.erb
<aside class="span4 sidebar notebook">
<%= image_tag("/assets/colorless/avatar.jpg", class: "portrait img-polaroid", height: '138', width: '136') %>
<h3>
  <span>About
  </span>
</h3>
<p>
&nbsp;&nbsp;89年Coder,&nbsp;爱互联网,&nbsp;爱海贼王.
</p>
<h3>
  <span>Tags</span>
</h3>
<p>
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_posts_tag_path(tag), :class => 'btn'%>
<% end %>
</p>

<h3>
  <span>
    Friends
  </span>
  <p>
  </p>
</h3>

</aside>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= yield :header %>
      <hr />
    </header>

    <%= yield :banner %>

    <div id="main">
      <div class="container">
        <%= render "layouts/flashes" %>
        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->

    <%= render "layouts/footer" %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_colorless_navbar.html.erb
<nav class="navbar">
<div class="navbar-inner">
  <div class="container">
    <h1>
      <a class="brand logo" title="Colorless Theme" href="/"><%= image_tag('/assets/colorless/blog_logo.png') %></a>
    </h1>
    <ul class="nav nav-pills hidden-phone pull-right">
      <li>
      <%= link_to 'Home', root_path %>
      </li>
      <li>
      <%= link_to 'Programming', '#' %>
      </li>
      <li>
        <%= link_to 'Essay', '#' %>
      </li>
    </ul>

  </div>

</div>
</nav>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>&copy; <%= Date.today.year %> <%= app_name %>. All rights reserved.</p>
    <p>Theme by <%= link_to "Dresssed", "http://dresssed.com" %>.</p>
  </div> <!-- /.container -->
</footer>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<div class="navbar navbar-fixed-top">
  <!-- TIP: to unfix the navbar:
    1. remove the 'navbar-fixed-top' class here and
    2. add the 'static-navbar' class to your body tag. -->
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Le logo -->
      <a class="brand" href="<%= admin_root_path %>"><%= app_name %></a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse">
        <ul class="nav">
          <%= activatable_li_tag_with_link "博客首页", root_path %>
        </ul> <!-- /.nav -->

        <%= yield :navbar %>
      </div> <!-- /.nav-collapse -->

    </div> <!-- /.container -->
  </div> <!-- /.navbar-inner -->
</div> <!-- /.navbar -->

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>
<div class="navbar-text pull-right">

  <% if admin_signed_in? %>
  <%= icon_tag "user" %> Welcome, <strong><%= current_admin.email %></strong>
    <span class="divider">|</span>
    <%= link_to 'Settings', edit_admin_registration_path %>
    <span class="divider">|</span>
    <%= link_to 'Logout', destroy_admin_session_path, :method => :delete %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<% content_for :navbar, render("layouts/user_nav") %>
<%= render :layout => "layouts/base" do %>
  <div class="page-header">
    <div class="row">
      <div class="span7">
        <h2><%= @title %></h2>
        <%= yield :description %>
      </div>
      <div class="span2">
        <%= yield :actions %>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class="row">
    <div id="content" class="span9">
      <%= yield %>
    </div> <!-- /#content -->

    <% if admin_signed_in? %>
      <div id="sidebar" class="span3">
        <h6>Menu</h6>
        <p></p>
        <ul class="nav nav-tabs nav-stacked nav-caret-left">
          <%= activatable_li_tag_with_link "文章管理", admin_posts_path %>
          <%= activatable_li_tag_with_link "Tag管理", admin_tags_path %>
          <%= activatable_li_tag_with_link "会员管理", '#' %>
        </ul>
      </div> <!-- /#sidebar -->
    <% end %>
  </div> <!-- /.row -->
<% end %>

app/views/layouts/colorless.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, Settings.blog.blog_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <meta content="#D6D6D6" name="color:Background Color">
    <meta content="#666666" name="color:Heading Background Color">
    <meta content="#3d3d3d" name="color:Text Color">
    <meta content="" name="image:Logo">
    <meta content="/assets/colorless/grid.png" name="image:Background Image">

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

     <%= auto_discovery_link_tag(:rss, posts_path(:rss)) %>

    <%= stylesheet_link_tag "colorless" %>
    <%= yield :styles %>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/colorless_navbar" %>
      <%= yield %>
      <footer>
        ©2013 hanluner.com . themes by <a href='http://themeforest.net/item/colorless-monochrome-tumblr-theme/3327623' target='_blank'>colorless</a>
      </footer>
    </div>
    <%= javascript_include_tag "colorless" %>
  </body>


<% end %>

app/views/layouts/home.html.erb
<% content_for :navbar do %>
  <%= form_tag "?", :class => "navbar-search pull-right" do %>
    <%= text_field_tag :query, params[:query], :class => "search-query" %>
  <% end %>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>